In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data/creditcard.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187259,127459.0,0.181802,-0.242352,0.947307,-1.922475,-0.533984,-0.232694,-0.145025,0.108437,-0.846039,...,0.077193,0.082471,0.147867,-0.376328,-0.729528,-0.559598,0.071644,0.043077,36.00,0
187260,127459.0,1.977822,-1.235799,-0.745133,-0.755697,-0.930876,-0.321549,-0.760046,-0.076025,0.129612,...,-0.163157,-0.653566,0.356817,0.633064,-0.480348,-0.612621,-0.014789,-0.019271,112.54,0
187261,127459.0,-6.143919,-4.912202,1.052520,0.791108,3.025188,0.389197,0.095249,-0.018539,0.857778,...,-0.923048,0.550598,2.426974,-1.689400,1.153145,-0.600711,-0.438160,1.276643,90.00,0
187262,127459.0,0.696691,-2.808154,-1.206833,-0.158734,-1.647400,-0.773182,0.318770,-0.268044,1.520876,...,0.242084,-0.794032,-0.184430,0.012931,-0.939578,0.265659,-0.171826,0.072771,700.00,0
187263,127459.0,-0.489190,0.783289,-1.659097,-1.366814,2.576846,3.513254,0.271305,1.304641,-0.238853,...,-0.058456,-0.214896,0.222998,0.675950,-0.632860,-0.530017,0.345872,0.221294,53.70,0

In [6]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,...,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000,187264.000000
mean,66587.949056,-0.129283,0.015409,0.388511,0.089845,-0.138218,0.052425,-0.063424,0.023265,0.012999,...,-0.019172,-0.062048,-0.018422,0.006143,0.073183,0.008806,0.001837,0.002113,88.892000,0.001965
std,31971.459773,1.880779,1.617750,1.426486,1.389641,1.355488,1.305975,1.211386,1.217263,1.142023,...,0.741124,0.682492,0.600368,0.601993,0.480903,0.489620,0.392653,0.309301,247.355572,0.044286
min,0.000000,-56.407510,-72.715728,-33.680984,-5.683171,-42.147898,-26.160506,-43.557242,-73.216718,-13.434066,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-11.710896,0.000000,0.000000
25%,42941.750000,-0.970585,-0.567713,-0.222286,-0.776256,-0.802460,-0.702238,-0.581193,-0.173701,-0.662008,...,-0.228331,-0.541481,-0.169262,-0.338092,-0.223756,-0.331096,-0.066562,-0.037249,5.917500,0.000000
50%,64517.000000,-0.123797,0.089167,0.547953,0.092247,-0.192783,-0.212191,-0.020182,0.048393,-0.075415,...,-0.047511,-0.047655,-0.031603,0.055336,0.116930,-0.060118,0.007053,0.019544,22.710000,0.000000
75%,83729.250000,1.201738,0.788861,1.255134,0.906789,0.428834,0.447137,0.483481,0.343017,0.631432,...,0.142402,0.399560,0.108941,0.419618,0.390366,0.266241,0.089344,0.078164,78.962500,0.000000
max,127459.000000,2.439207,22.057729,9.382558,16.875344,34.801666,22.529298,36.677268,20.007208,15.594995,...,27.202839,10.503090,19.002942,4.022866,7.519589,3.517346,12.152401,33.847808,19656.530000,1.000000

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

Class
0    186896
1       368
Name: count, dtype: int64

In [9]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
X

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
        -8.98309914e-03,  1.47241692e-02,  2.69000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.53527940e-02, -5.97518406e-02,  3.78660000e+02],
       ...,
       [ 1.27459000e+05, -6.14391945e+00, -4.91220179e+00, ...,
        -4.38159723e-01,  1.27664336e+00,  9.00000000e+01],
       [ 1.27459000e+05,  6.96691402e-01, -2.80815426e+00, ...,
        -1.71826202e-01,  7.27709715e-02,  7.00000000e+02],
       [ 1.27459000e+05, -4.89190215e-01,  7.83289483e-01, ...,
         3.45872332e-01,  2.21293505e-01,  5.37000000e+01]],
      shape=(187264, 30))

In [11]:
y

array([0, 0, 0, ..., 0, 0, 0], shape=(187264,))

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 7.38854211e-01,  7.66219031e-02,  5.52259604e-01, ...,
         5.37501715e-01,  2.41360056e-01, -3.03566041e-01],
       [-1.99373930e-01, -1.40678847e+00,  1.22808840e+00, ...,
        -1.60383492e+00,  1.58637345e+00, -3.53829845e-01],
       [ 4.59826789e-01,  6.81940194e-02,  6.29317508e-01, ...,
        -3.95498705e-01,  6.85774740e-02, -3.50985490e-01],
       ...,
       [ 4.14699205e-01, -8.48228978e-03,  6.00944548e-01, ...,
        -3.10224911e-01, -6.27490149e-01, -3.45093614e-01],
       [ 6.69316422e-01, -1.49135679e+00,  1.43574655e+00, ...,
         1.25193147e+00,  1.05465328e+00, -3.57039902e-01],
       [ 3.07857615e-01,  7.21719045e-01, -4.88786518e-01, ...,
        -9.64431071e-04,  1.14852817e-01,  9.80567852e-02]],
      shape=(149811, 30))

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
y_train_pred = classifier.predict(X_train)

In [17]:
from sklearn.metrics import confusion_matrix, f1_score
cm_train = confusion_matrix(y_train, y_train_pred)
print(cm_train)
f1_score(y_train, y_train_pred)

[[149507      6]
 [    47    251]]

0.9045045045045045

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
print(np.concatenate((y_pred.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

In [20]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
f1_score(y_test, y_pred)

[[37380     3]
 [   11    59]]

0.8939393939393939